#% -*- LaTeX -*-
#\DeclareLyXModule{@Custom: Electrical Engineering}
#
#DescriptionBegin
#Provides some electrical engineering and signal processing macros.
#DescriptionEnd
#Requires:
#Excludes:
#
# Copyright (C) 2012-2020 Ralf Hoppe <rho@dfcgen.de>
#

Format 35
Requires        amsmath
Provides        trfsigns 1


AddToPreamble

\usepackage{trfsigns}        %% symbols for FT, LT, ...
\input{electrical-inc}

EndPreamble
