#\DeclareLyXModule{Emphasized Environment}
#DescriptionBegin
#Provides an emphasized environment
#DescriptionEnd
# author: Ralf Hoppe <ralf.hoppe@ieee.org>

Format 11
Requires        color,framed

# Notice that renewing this environment does not work when using LaTeX2HTML,
# therefore set it here. In addition define color for use of package
# "framed" (for examples see /usr/share/texmf/tex/latex/graphics/color.sty)
# or that: \definecolor{shadecolor}{gray}{0.94}
#
# Uncomment this in Preamble when using LaTeX2HTML
# \usepackage{html,epsf}
# \latexhtml{\newenvironment{emphasized}{\begin{shaded}}{\end{shaded}}}
#           {\newenvironment{emphasized}{\HTMLcode{BR}\htmlrule*[width=90\%, size=4, align=center, NOSHADE]}{\htmlrule*[width=90\%, size=4, align=center, NOSHADE]\HTMLcode{BR}}}
#
# Notice that ifpackageloaded is normally not needed, but in this special
# case the packages framed.sty and the external wrapper tex4ht.sty are not
# compatible.

Style Emph(asized)
    LatexType       Environment
    LatexName       emphasized
    Margin          Dynamic
    InTitle         0
    TopSep          0.5
    BottomSep       0.5
    NextNoIndent    0
    PassThru        0
    FreeSpacing     0
    KeepEmpty       0
    Align           Left
    AlignPossible   Block, Left, Right, Center
    Fill_Top        0
    Fill_Bottom     0
    LabelType       Static
    LabelString     "Emph: "
    Labelsep        "M"

    Font
        Series      Bold
        Family      Typewriter
    EndFont

    LabelFont
        Series      Bold
        Size        large
        Color       Green
    EndFont

    Preamble
    \@ifpackageloaded{tex4ht}%
    {%
      \message{****************************************************************}%
      \message{* Environment emph(asized) redefined, incompatible with TeX4ht *}%
      \message{****************************************************************}%
      \newenvironment{emphasized}{}{}%
    }%
    {%
      \@ifpackageloaded{color}{}{\usepackage[usenames]{color}}%
      \usepackage{framed}%
      \definecolor{shadecolor}{cmyk}{0,0,0.5,0}%
      \newenvironment{emphasized}{\begin{shaded}}{\end{shaded}}%
    }
    EndPreamble
End

