#% -*- LaTeX -*-
#\DeclareLyXModule{@Custom: Basics and Helpers}
#DescriptionBegin
#Provides some helper macros, abbreviations and an emphasized environment.
#DescriptionEnd
#Requires: 
#Excludes:
#
# Copyright (C) 2012-2020 Ralf Hoppe <rho@dfcgen.de>
#

Format 35
Requires        pifont,textcomp,color,framed
Provides        helpers 1


AddToPreamble

\input{base-inc}

EndPreamble


Style Emph(asized)
    LatexType       Environment
    LatexName       emphasized
    Margin          Dynamic
    InTitle         0
    TopSep          0.5
    BottomSep       0.5
    NextNoIndent    0
    PassThru        0
    FreeSpacing     0
    KeepEmpty       0
    Align           Left
    AlignPossible   Block, Left, Right, Center
    LabelType       Static
    LabelString     "Emph: "
    Labelsep        "M"

    Font
        Series      Bold
        Family      Typewriter
    EndFont

    LabelFont
        Series      Bold
        Size        large
        Color       Green
    EndFont

    Preamble

    \@ifpackageloaded{tex4ht}%
    {%
      \message{Environment emph(asized) redefined, incompatible with TeX4ht}%
      \newenvironment{emphasized}{}{}%
    }%
    {%
      \@ifpackageloaded{color}{}{\usepackage[usenames]{color}}%
      \usepackage{framed}%
      \definecolor{shadecolor}{cmyk}{0,0,0.25,0}%
      \newenvironment{emphasized}{\begin{shaded}}{\end{shaded}}%
    }

    EndPreamble
End
