#% -*- LaTeX -*-
#\DeclareLyXModule{Extensions: Basic Styles and Helpers}
#DescriptionBegin
#Provides some helper macros, abbreviations and an emphasized environment.
#DescriptionEnd
#Requires: 
#Excludes:
#
# Copyright (C) 2012, 2013, 2015 Ralf Hoppe <ralf.hoppe@ieee.org>
#

Format 35
Requires        pifont,textcomp,color,framed

AddToPreamble

\usepackage{bibgerm}        % German bibliography
\usepackage[right]{eurosym} % EUR symbol & friends


%% for the following macros we must assign the '@' character to category
%% 'letter' (catcode 11), else you will get LaTeX errors
\makeatletter

%% definition of \provideenvironment{name}[narg]{begdef}{enddef} command
\def\provide@environment#1{%
  \@ifundefined{#1}{\relax}{%
  \expandafter\let\csname#1\endcsname\relax
  \expandafter\let\csname end#1\endcsname\relax
  \new@environment{#1}}}

%% You can derive some  \if\isdefined{} ... \else...\fi construct from this
\def\isdefined#1{\begingroup
    \expandafter\endgroup\expandafter\ifx
    \csname #1\endcsname\@undefined
    undefined\else defined\fi}


%%
%% Checks if a TeX job is equal to (file) name. This is tricky because
%% TeX macro \jobname expands to catcode 12 (other) characters.
%%
%% Example usage:
%%   \if\thisjob{name}%
%%   do this%
%%   \else%
%%   do that%
%%   \fi%
%% 
\def\thisjob#1{..\fi\begingroup
  \edef\jobA{\jobname}%
% Convert an arbitrary string to "other" characters:
% do \csname, \string, then \@gobble
  \edef\jobB{\expandafter \expandafter \expandafter \@gobble %
   \expandafter \string \csname #1\endcsname}%
  \expandafter \endgroup \ifx\jobA\jobB}


%%
%% Declares a package as already loaded - so LaTeX does not load it again (in
%% other words prevents LaTeX from using a package). But notice that this
%% command must be issued before \usepackage{package}.
%%
%% Example usage: \dontusepackage[opt1,opt2]{package}
\newcommand{\dontusepackage}[2][]{%
  \@namedef{ver@#2.sty}{9999/12/31}%
  \@namedef{opt@#2.sty}{#1}}


%% Some re- or extra definitions in case TeX4ht is (not) loaded
\@ifpackageloaded{tex4ht} {%
  %% breakurl.sty inserts special postscript code, which then is passed to
  %% the DVI page, then read by TeX4ht and finally passed to HTML page
  \PackageWarningNoLine{breakurl}{%
    Package breakurl not not compatible with TeX4ht...\MessageBreak
    \string\burl\space will be just a synonym of \string\url.}
  \DeclareRobustCommand{\burl}{\url}
  \DeclareRobustCommand*{\burlalt}{\hyper@normalise\burl@alt}
  \def\burl@alt#1#2{\hyper@linkurl{\Hurl{#1}}{#2}}
}{%
  %%
  %% Postscript font Times in text and math formulas (based on freely
  %% distributable fonts).
  %%
  %% Disadvantages:
  %% 1. No support of bold in math formulas (normally needed in headings, see
  %%    macro \headingmath in file math-inc.tex)
  %% 2. txfonts.sty collides with esint.sty (extended integral signs, see LyX)
  %%
  \usepackage{txfonts}
  \message{Using package txfonts...}
  %%  \usepackage{mathptmx}% automatic within LyX, when Times chosen
  %%
  %% Postscript font Palatino in text and math formulas (based on freely
  %% distributable fonts).
  %%
  %% \usepackage{pxfonts}                %% Declares \opentimes symbol)
  %% \usepackage[slantedGreek]{mathpazo} %% Palatino math
  %%
  %% Math fonts from mathdesign package for usage with standard LaTeX
  %% fonts
  %%
  %% \usepackage[garamond]{mathdesign}
}


%% Special commands/math/text in headings/titles
%% Usage: \toccmd{cmds}{replacement}
%% Example: \toccmd{\footnote{Test}}{}
\AtBeginDocument{
  \@ifpackageloaded{hyperref}{ %% hyperref loaded (PDF)
    \newcommand{\toccmd} [2] {\texorpdfstring{#1}{#2}}%
  }{ %% hyperref NOT loaded (no replacement)
    \newcommand{\toccmd} [2] {#1}%
  }
}

%% Normally '@' should be put back to category 'other' (catcode 12). But this
%% is done by LyX at the end of preamble.
%%
%% \makeatother


\newcommand{\re} {\mbox{bzgl.} }      %% regarding
\newcommand{\eg} {\mbox{z.\,B.} }     %% for example
\newcommand{\ie} {\mbox{d.\,h.} }     %% that is (id est)
\newcommand{\resp} {\mbox{bzw.} }     %% respective
\newcommand{\cf} {\mbox{vgl.} }       %% confer
\newcommand{\etc} {\mbox{usw.} }      %% et cetera


%% Compressed \cdot e.g. as used by Whittacker in paragraph numbers
\newcommand{\sdot} {\ensuremath{\! \cdot \!}}

\ifdefined\indexname
    \renewcommand{\indexname}{Stichwortverzeichnis}
\fi


%% Uncomment the following lines to suppress additional text added to a cite
%% command as optional argument (normally specific part/chapter/section number
%% links into the referenced work/paper
%%
%% \let\origcite\cite
%% \renewcommand{\cite} [2] [ignored] {\protect\origcite{#2}}

EndPreamble


Style Emph(asized)
    LatexType       Environment
    LatexName       emphasized
    Margin          Dynamic
    InTitle         0
    TopSep          0.5
    BottomSep       0.5
    NextNoIndent    0
    PassThru        0
    FreeSpacing     0
    KeepEmpty       0
    Align           Left
    AlignPossible   Block, Left, Right, Center
    LabelType       Static
    LabelString     "Emph: "
    Labelsep        "M"

    Font
        Series      Bold
        Family      Typewriter
    EndFont

    LabelFont
        Series      Bold
        Size        large
        Color       Green
    EndFont

    Preamble

    \makeatletter
    \@ifpackageloaded{tex4ht}%
    {%
      \message{Environment emph(asized) redefined, incompatible with TeX4ht}%
      \newenvironment{emphasized}{}{}%
    }%
    {%
      \@ifpackageloaded{color}{}{\usepackage[usenames]{color}}%
      \usepackage{framed}%
      \definecolor{shadecolor}{cmyk}{0,0,0.25,0}%
      \newenvironment{emphasized}{\begin{shaded}}{\end{shaded}}%
    }

    %% Normally '@' should be put back to category 'other' (catcode 12). But this
    %% is done by LyX at the end of preamble.
    %%
    %% \makeatother

    EndPreamble
End

