#\DeclareLyXModule{Extensions: Higher Math. Functions}
#
#DescriptionBegin
#My mathematical LaTeX command extensions
#DescriptionEnd
#Requires: 
#Excludes:
#
# Copyright (C) 2012 Ralf Hoppe <ralf.hoppe@ieee.org>
#

Format 35
Requires        array,ifthen,amssymb


AddToPreamble

\usepackage{amsopn,amsfonts}
\usepackage{trfsigns} %% symbols for FT, LT and e

%% FIXME: some changes in package array
%% \addtolength{\extrarowheight}{2pt}      %% extra vertical space in array (tabular family) environment
%% \addtolength{\jot}{2pt}                 %% extra vertical space in eqnarray environment

\newcommand{\tabvstretch} {\renewcommand{\arraystretch}{1.5}} % table/array vertical stretching
\newcommand{\tabvnormal}  {\renewcommand{\arraystretch}{1.0}} % reset to default


%% Optional superscript if exponent is unequal to zero
%% Requires \usepackage{ifthen}
%% Example: \optsup {0}{x} displays "x", \optsup {n}{x} displays "x^n"
\newcommand{\optsup} [2] {{#2} \ifthenelse{\equal{#1}{0}}{\mbox{}}{^{#1}}}

\newcommand{\incircle} [1] {\ensuremath{\mathbin{\settowidth{\dimen6}{\mbox{$\bigcirc$}}%
              \makebox[0pt][l]{$\bigcirc$}\makebox[\dimen6]{\small{#1}}}}}



%% Styles
\newcommand{\mbig} [1]    {\displaystyle{#1}}
\newcommand{\mboxed} [1] {\boxed{#1}}
\newcommand{\mvec} [1] {\ensuremath{\mathbf{#1}}} % Bold matrix/vector
\newcommand{\mdet} [1] {\mvec{#1}} % determinant variable
\newcommand{\avg} [1] {\overline{#1}} % average


%% Symbols, Variables, Constants
\newcommand{\ji} {\im} %% j from package trfsigns
\newcommand{\lps} {s}  %% Laplace variable s or p
\newcommand{\vp} {\,\textup{V.\,P.}} %% Cauchy principal value
%% \newcommand{\mequiv} {\ensuremath{\mathrel{\widehat{=}}}} %% equivalent: = with hat
\newcommand{\mequiv} {\ensuremath{\stackrel{\scriptscriptstyle\wedge}{=}}} %% equivalent: = with hat
\newcommand{\msp} {\ensuremath{\;}}% math space
\newcommand{\mperiod} {\msp.}      % period (at end of sentence) in math mode
\newcommand{\pdc} {\partial}       % partial differential character
\newcommand{\tdc} {\textup{d}}     % total differential character
\newcommand{\pic} {\,\pdc}         % partial differential with leading (thin) space
\newcommand{\tic} {\,\tdc}         % total differential with leading (thin) space

\ifx\opentimes\undefined %% \opentimes from px/txfonts packages loaded?
  \def\opentimes{\times}
\fi


%% Macros
\newcommand{\pdiff} [3] [0] {\frac{\optsup{#1}{\pdc} #2}{\pdc \optsup{#1}{#3}}}
\newcommand{\tdiff} [3] [0] {\frac{\optsup{#1}{\tdc} #2}{\tdc \optsup{#1}{#3}}}

%% Conjugate complexe value of a variable, function or expression
%% 
%% When the first (optional) argument is missing then the second will be
%% completely indicated as a conjugate complex value. When there is a
%% first argument then the second will be assumed as a function parameter.
%% In that case only the first argument is indicated as a conjugate complex
%% value and the second is shown only in normal parenthesis.
\newcommand{\cjgt} [2] [empty] {%
  \def\tempa{empty}%
  \def\tempb{#1}%
  \ifx\tempb\tempa
    #2^\ast%
  \else
    #1^\ast(#2)%
  \fi
}

%% \newcommand{\cjgt} [2] [] {%
%%   \ifx\\#1\\%
%%     \overline{#2}%
%%   \else
%%     \overline{#1(#2)}%
%%   \fi
%% }


\newcommand{\res} [2] {\residue_{#1} {#2}}  %% residue of function #2 at point #1
\newcommand{\rcls} [2] {{\left[ {#1} \right] }_{#2}} % residue class (algebra)

%% Simple Polynomial
%% Example: \poly{a}{x}{n} defines a polynomial in x with coefficients a[i]
%% from i=0 to i=n
\newcommand {\poly} [3] {\ensuremath{{#1}_{#3}{#2}^{#3}+\cdots +{#1}_2 {#2}^2+{#1}_1 {#2}+{#1}_0}}


%% Helpers
\newcommand{\tpar} [3] {#1;\, #2; #3}
\newcommand{\epar} [2] {#1;\, #2}
\newcommand{\spar} [1] {#1}


%% Functions (math operators)
%% \DeclareMathOperator{\imop}{\Im}
\DeclareMathOperator{\imop}{Im}         %% Imaginary part of complex number (Im{} operator)
%% \DeclareMathOperator{\reop}{\Re}
\DeclareMathOperator{\reop}{Re}         %% real part of complex number (Re{} operator)
\DeclareMathOperator{\ang}{\measuredangle}    %% angle of a complex number
%% \DeclareMathOperator{\ang}{\angle}   %% angle of a complex number
%% \DeclareMathOperator{\ang}{\arg}     %% angle of a complex number
\DeclareMathOperator{\residue}{res}     %% residue
\DeclareMathOperator{\expf}{e}          %% Exponential function

\DeclareMathOperator{\sign}{sgn}        %% Sign of an expression
\DeclareMathOperator{\cosec}{cosec}     %% 1/sin(x)
\DeclareMathOperator{\sech}{sech}       %% 1/cosh(x)
\DeclareMathOperator{\arsinh}{arsinh}
\DeclareMathOperator{\arcosh}{arcosh}
\DeclareMathOperator{\artanh}{artanh}
\DeclareMathOperator{\ld}{\log_{2}}      %% logaritmus dualis (ld)
\DeclareMathOperator{\gd}{gd}           %% Guderman function gd(x) = arctan(sinh(x))

\DeclareMathOperator{\pr}{\Pr}          %% Probability (sometimes only P)
\DeclareMathOperator{\cnorm}{\Phi}      %% Normal (cummulative) distribution
\DeclareMathOperator{\mean}{E}          %% Expected value (operator)
\DeclareMathOperator{\var}{Var}         %% Variance, e.g. \var X
\DeclareMathOperator{\cov}{Cov}         %% Covariance
\DeclareMathOperator{\corr}{Corr}       %% Correlation coefficient

\DeclareMathOperator{\lcm}{lcm}         %% Least Common Multiplier
\DeclareMathOperator{\ord}{ord}         %% Algebraic Order
\DeclareMathOperator{\GF}{GF}           %% Galois field
\DeclareMathOperator{\MONTG}{M}         %% Montgomery transformation
\DeclareMathOperator{\totient}{\phi}    %% Euler's totient function

\DeclareMathOperator{\rol}{rol}         %% Logic Rotate Left
\DeclareMathOperator{\ror}{ror}         %% Logic Rotate Right
\DeclareMathOperator{\shl}{shl}         %% Logic Shift Left
\DeclareMathOperator{\shr}{shr}         %% Logic Shift Right

\DeclareMathOperator{\Tn}{T} % Chebyshev functions (polynomials)
\DeclareMathOperator{\Un}{U}
\DeclareMathOperator{\sinc}{sinc} % sinc(x) = sin(x)/x


\newcommand{\zn} [3] [0] {\optsup{#1}{{#2}\kern-.24em\lower.68ex\hbox{$\scriptscriptstyle\circ$}}_{#3}}
%% \newcommand{\zn} [3] [0] {\optsup{#1}{{#2}_{\! \scriptscriptstyle \circ}}_{#3}}
\newcommand{\pn} [3] [0] {\optsup{#1}{{#2}\kern-.24em\lower.68ex\hbox{$\scriptscriptstyle\opentimes$}}_{#3}}
%% \newcommand{\pn} [3] [0] {\optsup{#1}{{#2}_{\! \scriptscriptstyle \infty}}_{#3}}


%% Integral transformations (FT, LT, ZT, DFT, ...) and \e, \im from trfsigns
\DeclareMathOperator{\ft} {\mathcal F}  %% Fourier-Transform
\DeclareMathOperator{\lt} {\mathcal L}  %% Laplace-Transform
\DeclareMathOperator{\zt} {\mathcal Z}  %% Z-Transform

\newcommand{\lft} [1] [] {\allowbreak\;\laplace{#1}\allowbreak\;}    %% Continuous Fourier transform (left time domain)
\newcommand{\rft} [1] [] {\allowbreak\;\Laplace{#1}\allowbreak\;}    %% Continuous Fourier transform (right time domain)
\newcommand{\lpt} [1] [] {\allowbreak\;\laplace{#1}\allowbreak\;}    %% Continuous Laplace transform (left time domain)
\newcommand{\rlt} [1] [] {\allowbreak\;\Laplace{#1}\allowbreak\;}    %% Continuous Laplace transform (right time domain)


%% for the following macros we must assign the '@' character to category
%% 'letter' (catcode 11), else you will get LaTeX errors
\makeatletter

%% Fractions look extremely ugly in tables, because there is no space over
%% and under. The following macro writes a fbox without a frame but with the
%% fboxsep. But this does not work on some HTML converters.
\@ifpackageloaded{tex4ht}{      %
  \newcommand{\mtab} [1] {      % math in tables
    \ensuremath{\mbig{#1}}}}{   %
  \newcommand{\mtab} [1] {      %
    \setlength{\fboxrule}{0pt}  %
    \fbox{\ensuremath{\mbig{#1}}}}}



%% Inline math in headings/titles
%% Usage: \tocmath{expr}{replacement}
%% Example: \tocmath{x^y}{x times y}
\AtBeginDocument{
  \@ifpackageloaded{hyperref}{ %% hyperref loaded (PDF)
    \newcommand{\tocmath} [2] {%
      \texorpdfstring{%
        \mathversion{bold}%
        \ensuremath{#1}%
        \mathversion{normal}}{#2}}%
  }{ %% hyperref NOT loaded (no replacement)
    \newcommand{\tocmath} [2] {\ensuremath{#1}}}
}

%% Normally '@' should be put back to category 'other' (catcode 12). But this
%% is done by LyX at the end of preamble.
%%
%% \makeatother

EndPreamble

