#\DeclareLyXModule{Synopsis}
#DescriptionBegin
#Provides a list environment for synopsis (commands, typewriter based)
#DescriptionEnd
# author: Ralf Hoppe <ralf.hoppe@ieee.org>

Format 11

Style Synopsis
	Category        List
    LatexType       List_Environment
    LatexName       synopsis
    Margin          Manual
    NextNoIndent    1
	LabelSep        xxx
	ParSkip         0.4
	TopSep          0.7
	BottomSep       0.7
	ParSep          0.2
	Align           Block
	AlignPossible   Block, Left
	LabelType       Manual
	LabelString     "12em"

    LabelFont
        Family      Typewriter
        Color       Blue
    EndFont

    Requires        ifthen


	#define the environment synopsis
	Preamble
        \newlength{\synopsisLabelWidth}
        \newcommand{\synopsisMakeLabel} [1] {%
            \settowidth{\synopsisLabelWidth}{\texttt{#1}}%
            \ifthenelse{\lengthtest{\synopsisLabelWidth > \labelwidth}}%
                       {\parbox[b]{\labelwidth}{\makebox[0pt][l]{\texttt{#1}}\newline}}%
                       {\texttt{#1}}%
            \hfil\relax}
		\newenvironment{synopsis}[1]
			           {\begin{list}{}{
                             \setlength{\labelwidth}{#1}
                             \setlength{\leftmargin}{\labelwidth}
				             \addtolength{\leftmargin}{\labelsep}
                             \let\makelabel\synopsisMakeLabel}}
			           {\end{list}}
	EndPreamble

#  \renewcommand{\makelabel}[1]{\synopsisMakeLabel{##1}}}} %

End

